### ISSUE TITLE
Error: SocketException: Protocol family unavailable

### ISSUE THREAD

**Issue by cemerick** [cemerick/nREPL#20]
The description in NREPL-83 suggests "start-server" will try "::" first and then fall back to "localhost". However, running in Alpine Linux, the attempt to bind "::" throws an exception and the fallback to "localhost" never occurs.

AFAIK, Alpine is different in more ways than one... ipv6 disabled by default, and also musl-libc has its own resolver, so multiple factors could be adding up here. The result however is an exception and behavior that doesn't match the expectation established in NREPL-83.

Obviously the caller can workaround this problem by explicitly passing a :bind argument, like (start-server :port p :bind "localhost"), and for that reason I can consider this a minor issue. If nothing else perhaps the documentation can be clarified.

Here' a transcript to show what I mean:
https://gist.github.com/gonewest818/ae5c5caf49380f81c5a2667408da6d4f

lines 1-74 documents launching alpine, installing lein, and creating a project with nrepl 0.2.13

lines 75-76 shows the exception when no :bind is specified

lines 78-79 proves the obvious workaround

lines 90-91 duplicates the exception by replicating what's happening inside tools.repl

(from https://dev.clojure.org/jira/browse/NREPL-87)

**Comment by cemerick** [comment]
I ran into this in the process of setting up travis-ci; within its environments, ipv6 `::` is resolved, but cannot be bound. Fixed by https://github.com/cemerick/nREPL/commit/36c77ddb03f2499f8b95701148a73d6d809b081d.

Note that this is the sole difference between the forthcoming `0.3.0` release and `[org.clojure/tools.nrepl "0.2.13"]`.

**Comment by bbatsov** [comment]
👍  This was also plaguing `cider-nrepl`'s build for a while.
